repos:
  # Detect secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: '(^fish/fish_variables$|.*lock\.json$)'

  # General security checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Git secrets (commenting out - requires API key)
  # - repo: https://github.com/gitguardian/ggshield
  #   rev: v1.25.0
  #   hooks:
  #     - id: ggshield
  #       language: python
  #       stages: [pre-commit]
