repos:
  # Detect secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: '(^fish/fish_variables$|.*lock\.json$)'
      # Secondary targeted scan for fish/fish_variables without entropy detectors
      - id: detect-secrets
        name: detect-secrets (fish variables, no entropy)
        entry: detect-secrets scan --no-follow-symlinks --all-files \
          --disable-plugin Base64HighEntropyString \
          --disable-plugin HexHighEntropyString \
          --fail-on-secrets fish/fish_variables
        language_version: python3
        pass_filenames: false
        files: '^fish/fish_variables$'
        stages: [pre-commit]

  # General security checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Git secrets (commenting out - requires API key)
  # - repo: https://github.com/gitguardian/ggshield
  #   rev: v1.25.0
  #   hooks:
  #     - id: ggshield
  #       language: python
  #       stages: [pre-commit]
