# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

vimcmd_symbol = '[](bold green)'
vimcmd_visual_symbol = '[](bold yellow)'
vimcmd_replace_symbol = '[](bold purple)'
vimcmd_replace_one_symbol = '[](bold purple)'

