# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 9000

# Inserts a blank line between shell prompts
add_newline = true

[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

vimcmd_symbol = '[](bold green)'
vimcmd_visual_symbol = '[](bold yellow)'
vimcmd_replace_symbol = '[](bold purple)'
vimcmd_replace_one_symbol = '[](bold purple)'

[git_status]
format = '($all_status$ahead_behind )'
ahead = '[↑${count}](green)'
behind = '[↓${count}](red)'
diverged = '[↑${ahead_count}](green) [↓${behind_count}](red)'

[username]
disabled = true
[hostname]
disabled = true
