theme = "custom"
transparent_background = true

[custom_theme]
base = "nord"
label = "Nord+"

accent = "#88C0D0"
badgeAdded = "#A3BE8C"
badgeRemoved = "#BF616A"
fileNew = "#A3BE8C"
fileDeleted = "#BF616A"
fileModified = "#81A1C1"
fileRenamed = "#B48EAD"
fileUntracked = "#D08770"
