compact = false
provider = "radio"
shuffle = false
theme = "nord"

visualizer = "Bricks"
repeat = "One"
eq_preset = "Jazz"
eq = [3, 4, 2, 1, -1, -1, 1, 2, 3, 4]

speed = 1.00
[soundcloud]
enabled = true
user = "serious-jack"
cookies_from = "safari"

[spotify]
bitrate   = 320
