compact = false
provider = "radio"
shuffle = false
theme = "nord"

visualizer = "Binary"
repeat = "One"
eq_preset = "Flat"
eq = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[soundcloud]
enabled = true
user = "serious-jack"
cookies_from = "safari"

[spotify]
bitrate   = 320
