[[station]]
name = "Full Spectrum Radio - DnB | Jungle | Dubstep | Electronic"
url = "https://fullspectrumradio.com/listen"
country = "Canada"
bitrate = 320
codec = "MP3"
homepage = "https://fullspectrumradio.com/"

[[station]]
name = "Radio Caprice LIQUID FUNK / INTELLIGENT / ATMOSPHERIC DRUM'n'BASS"
url = "http://79.111.119.111:8000/liquidfunk"
country = "The Russian Federation"
bitrate = 320
codec = "AAC+"
tags = "drum 'n' bass,funk"
homepage = "http://radcap.ru/liquidfunk.html"

[[station]]
name = "drumfunk.ru"
url = "https://ice.drumfunk.ru:8050/on.mp3"
country = "The Russian Federation"
bitrate = 192
codec = "MP3"
tags = "breakcore"
homepage = "https://drumfunk.ru/"

[[station]]
name = "Deep House Lounge"
url = "http://198.15.94.34:8006/stream"
country = "The United States Of America"
bitrate = 128
codec = "MP3"
tags = "deep house,disco,electronica,funky,house,jazzy,lounge,philadelphia,techno"
homepage = "http://www.deephouselounge.com/"

[[station]]
name = "101 SMOOTH JAZZ"
url = "http://jking.cdnstream1.com/b22139_128mp3"
country = "The United States Of America"
bitrate = 128
codec = "MP3"
tags = "easy listening,jazz,smooth jazz"
homepage = "http://101smoothjazz.com/"

[[station]]
name = "Radio Caprice - Future Garage / Chillstep / Deep / Post Dubstep"
url = "http://79.120.39.202:8002/futuregarage"
country = "The Russian Federation"
bitrate = 48
codec = "AAC+"
tags = "chillstep,deep,future garage,post dubstep,radcap"
homepage = "http://radcap.ru/futuregarage.html"
