[[station]]
name = "Full Spectrum Radio - DnB | Jungle | Dubstep | Electronic"
url = "https://fullspectrumradio.com/listen"
country = "Canada"
bitrate = 320
codec = "MP3"
homepage = "https://fullspectrumradio.com/"

[[station]]
name = "Radio Caprice LIQUID FUNK / INTELLIGENT / ATMOSPHERIC DRUM'n'BASS"
url = "http://79.111.119.111:8000/liquidfunk"
country = "The Russian Federation"
bitrate = 320
codec = "AAC+"
tags = "drum 'n' bass,funk"
homepage = "http://radcap.ru/liquidfunk.html"

[[station]]
name = "drumfunk.ru"
url = "https://ice.drumfunk.ru:8050/on.mp3"
country = "The Russian Federation"
bitrate = 192
codec = "MP3"
tags = "breakcore"
homepage = "https://drumfunk.ru/"

[[station]]
name = "Deep House Lounge"
url = "http://198.15.94.34:8006/stream"
country = "The United States Of America"
bitrate = 128
codec = "MP3"
tags = "deep house,disco,electronica,funky,house,jazzy,lounge,philadelphia,techno"
homepage = "http://www.deephouselounge.com/"

[[station]]
name = "101 SMOOTH JAZZ"
url = "http://jking.cdnstream1.com/b22139_128mp3"
country = "The United States Of America"
bitrate = 128
codec = "MP3"
tags = "easy listening,jazz,smooth jazz"
homepage = "http://101smoothjazz.com/"

[[station]]
name = "Radio Caprice - Future Garage / Chillstep / Deep / Post Dubstep"
url = "http://79.120.39.202:8002/futuregarage"
country = "The Russian Federation"
bitrate = 48
codec = "AAC+"
tags = "chillstep,deep,future garage,post dubstep,radcap"
homepage = "http://radcap.ru/futuregarage.html"

[[station]]
name = "Radio Caprice - Breakcore"
url = "http://79.111.119.111:8004/breakcore"
country = "The Russian Federation"
bitrate = 320
codec = "AAC+"
tags = "breakcore,electronic,idm"
homepage = "http://radcap.ru/breakcore.html"

[[station]]
name = "Adroit Jazz Underground"
url = "https://icecast.walmradio.com:8443/jazz"
country = "The United States Of America"
bitrate = 320
codec = "MP3"
tags = "avant-garde,bebop,big band,bop,combos,contemporary,contemporary jazz,cool,cool jazz,free jazz,fusion,hard bop,hd,mainstream,mainstream jazz,modern,modern big band,post-bop,straight-ahead,walm,west coast"
homepage = "https://walmradio.com/jazz"

[[station]]
name = "Jazz Lounge"
url = "http://eu8.fastcast4u.com:5068/;"
country = "Malaysia"
bitrate = 320
codec = "MP3"
tags = "320kbps,classic jazz,jazz,smooth jazz"
homepage = "http://shoutcast.flashradio.info/#/Jazz/1292701/"

[[station]]
name = "dubtechno247station"
url = "http://135.148.46.104:8010/radio.mp3"
country = "The United States Of America"
bitrate = 128
codec = "MP3"
