complete -c mcat -s o -l output -d 'Output format' -r -f -a "html\t''
md\t''
image\t''
video\t''
inline\t''
interactive\t''"
complete -c mcat -s t -l theme -d 'Color theme [default: nord]' -r -f -a "catppuccin\t''
nord\t''
monokai\t''
dracula\t''
gruvbox\t''
one_dark\t''
solarized\t''
tokyo_night\t''
makurai_light\t''
makurai_dark\t''
ayu\t''
ayu_mirage\t''
github\t''
synthwave\t''
material\t''
rose_pine\t''
kanagawa\t''
vscode\t''
everforest\t''
autumn\t''
spring\t''"
complete -c mcat -l md-image -d 'what images to render in the markdown [default: auto]' -r -f -a "all\t''
small\t''
none\t''
auto\t''"
complete -c mcat -l color -d 'Control ANSI formatting [default: auto]' -r -f -a "never\t''
always\t''
auto\t''"
complete -c mcat -l pager -d 'Modify the default pager [default: \'less -r\']' -r
complete -c mcat -l paging -d 'Control paging behavior [default: auto]' -r -f -a "never\t''
always\t''
auto\t''"
complete -c mcat -l opts -d 'Options for --output inline: *  center=<bool> *  inline=<bool> *  width=<string> *  height=<string> *  scale=<f32> *  spx=<string> *  sc=<string> *  zoom=<usize> *  x=<int> *  y=<int> Example: --opts \'center=false,inline=true,width=80%,height=20c,scale=0.5,spx=1920x1080,sc=100x20xforce,zoom=2,x=16,y=8\'' -r
complete -c mcat -l sort -d 'sort method for the ls command [default: name]' -r -f -a "name\t''
size\t''
time\t''
type\t''"
complete -c mcat -l ls-opts -d 'Options for directory listings: *  x_padding=<string> *  y_padding=<string> *  min_width=<string> *  max_width=<string> *  height=<string> *  items_per_row=<usize> Example: --ls-opts \'x_padding=4c,y_padding=2c,min_width=4c,max_width=16c,height=8%,items_per_row=12\'' -r
complete -c mcat -l generate -d 'Generate shell completions' -r -f -a "bash\t''
zsh\t''
fish\t''
powershell\t''"
complete -c mcat -l no-linenumbers -d 'Disable line numbers in code blocks'
complete -c mcat -s f -d 'sets md-image to none, for speed.'
complete -c mcat -l header -d 'shows YAML headers too'
complete -c mcat -s C -d 'Shortcut for --color never'
complete -c mcat -s c -d 'Shortcut for --color always'
complete -c mcat -s P -d 'Shortcut for --paging never'
complete -c mcat -s p -d 'Shortcut for --paging always'
complete -c mcat -s i -d 'Shortcut for --output inline'
complete -c mcat -s I -d 'Shortcut for --output interactive'
complete -c mcat -s s -l style-html -d 'Add style to HTML output (when HTML is the output)'
complete -c mcat -l report -d 'Reports image/video dimensions and additional info'
complete -c mcat -l silent -d 'Removes loading bars'
complete -c mcat -l kitty -d 'Use Kitty image protocol'
complete -c mcat -l iterm -d 'Use iTerm2 image protocol'
complete -c mcat -l sixel -d 'Use Sixel image protocol'
complete -c mcat -l ascii -d 'Use ASCII art output'
complete -c mcat -l hori -d 'Concatenate images horizontally'
complete -c mcat -l delete-images -d 'Delete all images (Kitty only)'
complete -c mcat -s a -l hidden -d 'Include hidden files'
complete -c mcat -l hyprlink -d 'adds hyprlink to the text in the ls command'
complete -c mcat -s X -d 'shortcut for --sort type'
complete -c mcat -s S -d 'shortcut for --sort size'
complete -c mcat -s r -l reverse -d 'reverse the order of items in the ls command'
complete -c mcat -l fetch-chromium -d 'Download and prepare chromium'
complete -c mcat -l fetch-ffmpeg -d 'Download and prepare ffmpeg'
complete -c mcat -l fetch-clean -d 'Clean up local binaries'
complete -c mcat -s h -l help -d 'Print help'
complete -c mcat -s V -l version -d 'Print version'
