complete -c onefetch -s d -l disabled-fields -d 'Allows you to disable FIELD(s) from appearing in the output' -r -f -a "project\t''
description\t''
head\t''
pending\t''
version\t''
created\t''
languages\t''
dependencies\t''
authors\t''
last-change\t''
contributors\t''
url\t''
commits\t''
churn\t''
lines-of-code\t''
size\t''
license\t''"
complete -c onefetch -l number-of-authors -d 'Maximum NUM of authors to be shown' -r
complete -c onefetch -l number-of-languages -d 'Maximum NUM of languages to be shown' -r
complete -c onefetch -l number-of-file-churns -d 'Maximum NUM of file churns to be shown' -r
complete -c onefetch -l churn-pool-size -d 'Minimum NUM of commits from HEAD used to compute the churn summary' -r
complete -c onefetch -s e -l exclude -d 'Ignore all files & directories matching EXCLUDE' -r
complete -c onefetch -l no-bots -d 'Exclude [bot] commits. Use <REGEX> to override the default pattern' -r
complete -c onefetch -s T -l type -d 'Filters output by language type' -r -f -a "programming\t''
markup\t''
prose\t''
data\t''"
complete -c onefetch -s t -l text-colors -d 'Changes the text colors (X X X...)' -r
complete -c onefetch -l number-separator -d 'Which thousands SEPARATOR to use' -r -f -a "plain\t''
comma\t''
space\t''
underscore\t''"
complete -c onefetch -l ascii-input -d 'Takes a non-empty STRING as input to replace the ASCII logo' -r -f -a "(__fish_complete_command)"
complete -c onefetch -s c -l ascii-colors -d 'Colors (X X X...) to print the ascii art' -r
complete -c onefetch -s a -l ascii-language -d 'Which LANGUAGE\'s ascii art to print' -r -f -a "abnf\t''
abap\t''
ada\t''
agda\t''
arduino\t''
assembly\t''
ats\t''
autohotkey\t''
bash\t''
c\t''
cmake\t''
c#\t''
ceylon\t''
clojure\t''
coffeescript\t''
coldfusion\t''
coq\t''
c++\t''
crystal\t''
css\t''
cuda\t''
d\t''
dart\t''
dockerfile\t''
emacs-lisp\t''
elixir\t''
elm\t''
emojicode\t''
erlang\t''
f#\t''
fish\t''
forth\t''
fortran\t''
fortranmodern\t''
gdscript\t''
glsl\t''
go\t''
graphql\t''
groovy\t''
haskell\t''
haxe\t''
hcl\t''
hlsl\t''
holyc\t''
html\t''
idris\t''
java\t''
javascript\t''
json\t''
jsonnet\t''
jsx\t''
julia\t''
jupyter-notebooks\t''
kotlin\t''
llvm\t''
lean\t''
lisp\t''
lua\t''
makefile\t''
markdown\t''
modelica\t''
nim\t''
nix\t''
ocaml\t''
objective-c\t''
odin\t''
openscad\t''
org\t''
oz\t''
pascal\t''
perl\t''
php\t''
powershell\t''
processing\t''
prolog\t''
protocol-buffers\t''
purescript\t''
python\t''
qml\t''
r\t''
racket\t''
raku\t''
razor\t''
renpy\t''
ruby\t''
rust\t''
sass\t''
scala\t''
scheme\t''
shell\t''
solidity\t''
sql\t''
svelte\t''
svg\t''
swift\t''
systemverilog\t''
tcl\t''
tex\t''
text\t''
toml\t''
tsx\t''
typescript\t''
typst\t''
vala\t''
verilog\t''
vhdl\t''
vimscript\t''
visualbasic\t''
vue\t''
webassembly\t''
wolfram\t''
xsl\t''
xaml\t''
xml\t''
yaml\t''
zig\t''
zsh\t''"
complete -c onefetch -l true-color -d 'Specify when to use true color' -r -f -a "auto\t''
never\t''
always\t''"
complete -c onefetch -s i -l image -d 'Path to the IMAGE file' -r -F
complete -c onefetch -l image-protocol -d 'Which image PROTOCOL to use' -r -f -a "kitty\t''
sixel\t''
iterm\t''"
complete -c onefetch -l color-resolution -d 'VALUE of color resolution to use with SIXEL backend' -r -f -a "16\t''
32\t''
64\t''
128\t''
256\t''"
complete -c onefetch -s o -l output -d 'Outputs Onefetch in a specific format' -r -f -a "json\t''
yaml\t''"
complete -c onefetch -l generate -d 'If provided, outputs the completion file for given SHELL' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c onefetch -l no-title -d 'Hides the title'
complete -c onefetch -l no-merges -d 'Ignores merge commits'
complete -c onefetch -s E -l email -d 'Show the email address of each author'
complete -c onefetch -l http-url -d 'Display repository URL as HTTP'
complete -c onefetch -l hide-token -d 'Hide token in repository URL'
complete -c onefetch -l include-hidden -d 'Count hidden files and directories'
complete -c onefetch -s z -l iso-time -d 'Use ISO 8601 formatted timestamps'
complete -c onefetch -l no-bold -d 'Turns off bold formatting'
complete -c onefetch -l no-color-palette -d 'Hides the color palette'
complete -c onefetch -l no-art -d 'Hides the ascii art or image if provided'
complete -c onefetch -l nerd-fonts -d 'Use Nerd Font icons'
complete -c onefetch -s l -l languages -d 'Prints out supported languages'
complete -c onefetch -s p -l package-managers -d 'Prints out supported package managers'
complete -c onefetch -s h -l help -d 'Print help (see more with \'--help\')'
complete -c onefetch -s V -l version -d 'Print version'
