volumes:
  omniroute_data:
  omniroute_redis_data:

services:
  omniroute:
    image: diegosouzapw/omniroute:3.8.7 # latest
    restart: unless-stopped
    stop_grace_period: 40s
    mem_limit: 512m
    memswap_limit: 1024m
    environment:
      - PORT=20128
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_BASE_URL=https://router.mjdgme.easypanel.host
      - REDIS_URL=redis://redis:6379
      - OMNIROUTE_MEMORY_MB=373
      - INITIAL_PASSWORD='!1Qaz2Wsx'
      - OMNIROUTE_WS_BRIDGE_SECRET=n5tRZK6vszYjAH8EHrkbFwh2P3eyW6U84Wm92QvVqvY
    volumes:
      - omniroute_data:/app/data
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    mem_limit: 64m
    volumes:
      - omniroute_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
