# Single path (works as before, no tabs)
tries_path = "~/dev/tries/"

editor = "nvim"               # Optional: code, nvim, hx, etc.
apply_date_prefix = false     # optional, default is false
transparent_background = true # optional, default is true (uses terminal background)

# ui configuration
show_right_panel = true # optional, default is true
right_panel_width = 25  # optional, right panel width in percentage (20-80)
show_disk = true        # optional, default is true
show_preview = true     # optional, default is true
show_legend = true      # optional, default is true

# Theme configuration (choose one of the available themes)
theme = "Nord"
