sort_order = ["config", "tmux", "zoxide"]

blacklist = ["scratch"]

[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "dotfiles"
path = "~/dev/dotfiles"

[[session]]
name = "vault"
path = "~/vaults/obsidian"
