[mcp_servers.mcpproxy]
type = "http"
url = "http://localhost:8080/mcp"

[mcp_servers.pencil]
command = "/Applications/Pencil.app/Contents/Resources/app.asar.unpacked/out/mcp-server-darwin-arm64"
args = [ "--app", "desktop" ]

[plugins."github@openai-curated"]
enabled = true

[plugins."google-drive@openai-curated"]
enabled = true

[plugins."caveman@caveman-repo"]
enabled = true

[marketplaces.caveman-repo]
last_updated = "2026-04-24T21:28:26Z"
last_revision = "84cc3c14fa1e10182adaced856e003406ccd250d"
source_type = "git"
source = "https://github.com/JuliusBrussee/caveman.git"
