[[track]]
path = "https://soundcloud.com/vykhod_sily/vykhod-sily-podcast-whattman-guest-mix"
title = "Vykhod Sily Podcast - Whatmann Guest Mix"

[[track]]
path = "https://soundcloud.com/irp_mail/cheshire-cat-dub"
title = "Cheshire Cat Dub"

[[track]]
path = "https://soundcloud.com/irp_mail/step-easy-swing-easy-riddim"
title = "Step Easy (Swing Easy Riddim)"

[[track]]
path = "https://www.youtube.com/watch?v=M653ML3FRNM"
title = "🎶 The Unreal Radio Stream⚡️WINAMP plays Unreal Tournament OST 🤘"
artist = "Nanotech Studios"
