[[track]]
path = "https://ice6.somafm.com/groovesalad-128-mp3"
title = "[SomaFM] Groove Salad: A nicely chilled plate of ambient/downtempo beats and grooves."

[[track]]
path = "https://ice6.somafm.com/groovesalad2-128-mp3"
title = "[SomaFM] Groove Salad 2: A different mix of nicely chilled ambient/downtempo beats and grooves."

[[track]]
path = "https://ice6.somafm.com/gsclassic-128-mp3"
title = "[SomaFM] Groove Salad Classic: The classic (early 2000s) version of a nicely chilled plate of ambient/downtempo beats and grooves."

[[track]]
path = "https://ice6.somafm.com/beatblender-128-mp3"
title = "[SomaFM] Beat Blender: A late night blend of deep-house and downtempo chill."

[[track]]
path = "https://ice6.somafm.com/deepspaceone-128-mp3"
title = "[SomaFM] Deep Space One: Deep ambient electronic, experimental and space music. For inner and outer space exploration."

[[track]]
path = "https://ice6.somafm.com/dronezone-128-mp3"
title = "[SomaFM] Drone Zone: Served best chilled, safe with most medications. Atmospheric textures with minimal beats."

[[track]]
path = "https://ice6.somafm.com/dz2-128-mp3"
title = "[SomaFM] Drone Zone 2: A more eclectic alternative mix of atmospheric textures with minimal beats."

[[track]]
path = "https://ice6.somafm.com/dubstep-128-mp3"
title = "[SomaFM] Dub Step Beyond: Dubstep, Dub and Deep Bass. May damage speakers at high volume."

[[track]]
path = "https://ice6.somafm.com/missioncontrol-128-mp3"
title = "[SomaFM] Mission Control: Celebrating NASA and Space Explorers everywhere."

# [[track]]
# path = "https://ice6.somafm.com/secretagent-128-mp3"
# title = "[SomaFM] Secret Agent: The soundtrack for your stylish, mysterious, dangerous life. For Spies and PIs too!"

[[track]]
path = "https://ice6.somafm.com/7soul-128-mp3"
title = "[SomaFM] Seven Inch Soul: Vintage soul tracks from the original 45 RPM vinyl."

[[track]]
path = "https://ice6.somafm.com/sf1033-128-mp3"
title = "[SomaFM] SF 10-33: Ambient music mixed with the sounds of San Francisco public safety radio traffic."

[[track]]
path = "https://ice6.somafm.com/sonicuniverse-128-mp3"
title = "[SomaFM] Sonic Universe: Transcending the world of jazz with eclectic, avant-garde takes on tradition."

[[track]]
path = "https://ice6.somafm.com/spacestation-128-mp3"
title = "[SomaFM] Space Station Soma: Tune in, turn on, space out. Spaced-out ambient and mid-tempo electronica."

[[track]]
path = "https://ice6.somafm.com/specials-128-mp3"
title = "[SomaFM] Specials: Now featuring Afternoon Jazz, Wavepool, DubX, The Surf Report & More!"

[[track]]
path = "https://ice6.somafm.com/synphaera-128-mp3"
title = "[SomaFM] Synphaera Radio: Featuring the music from an independent record label focused on modern electronic ambient and space music."

[[track]]
path = "https://ice6.somafm.com/insound-128-mp3"
title = "[SomaFM] The In-Sound: 60s/70s Hipster Euro Pop where psychedelic melodies meets groovy vibes."
