[[track]]
path = "https://somafm.com/groovesalad.pls"
title = "[SomaFM] Groove Salad: A nicely chilled plate of ambient/downtempo beats and grooves."

[[track]]
path = "https://somafm.com/groovesalad2.pls"
title = "[SomaFM] Groove Salad 2: A different mix of nicely chilled ambient/downtempo beats and grooves."

[[track]]
path = "https://somafm.com/gsclassic.pls"
title = "[SomaFM] Groove Salad Classic: The classic (early 2000s) version of a nicely chilled plate of ambient/downtempo beats and grooves."

[[track]]
path = "https://somafm.com/beatblender.pls"
title = "[SomaFM] Beat Blender: A late night blend of deep-house and downtempo chill."

[[track]]
path = "https://somafm.com/deepspaceone.pls"
title = "[SomaFM] Deep Space One: Deep ambient electronic, experimental and space music. For inner and outer space exploration."

[[track]]
path = "https://somafm.com/brfm.pls"
title = "[SomaFM] Black Rock FM: From the Black Rock Desert playa to the world, year round!"

[[track]]
path = "https://somafm.com/cliqhop.pls"
title = "[SomaFM] cliqhop IDM: Blips'n'beeps backed mostly w/beats. Intelligent Dance Music."

[[track]]
path = "https://somafm.com/doomed.pls"
title = "[SomaFM] Doomed: Dark industrial/ambient music for tortured souls. Where every day is Halloween."

[[track]]
path = "https://somafm.com/dronezone.pls"
title = "[SomaFM] Drone Zone: Served best chilled, safe with most medications. Atmospheric textures with minimal beats."

[[track]]
path = "https://somafm.com/dz2.pls"
title = "[SomaFM] Drone Zone 2: A more eclectic alternative mix of atmospheric textures with minimal beats."

[[track]]
path = "https://somafm.com/dubstep.pls"
title = "[SomaFM] Dub Step Beyond: Dubstep, Dub and Deep Bass. May damage speakers at high volume."

[[track]]
path = "https://somafm.com/fluid.pls"
title = "[SomaFM] Fluid: Drown in the electronic sound of instrumental hiphop, future soul and liquid trap."

[[track]]
path = "https://somafm.com/reggae.pls"
title = "[SomaFM] Heavyweight Reggae: Reggae, Ska, Rocksteady classic and deep tracks."

[[track]]
path = "https://somafm.com/missioncontrol.pls"
title = "[SomaFM] Mission Control: Celebrating NASA and Space Explorers everywhere."

[[track]]
path = "https://somafm.com/secretagent.pls"
title = "[SomaFM] Secret Agent: The soundtrack for your stylish, mysterious, dangerous life. For Spies and PIs too!"

[[track]]
path = "https://somafm.com/7soul.pls"
title = "[SomaFM] Seven Inch Soul: Vintage soul tracks from the original 45 RPM vinyl."

[[track]]
path = "https://somafm.com/sf1033.pls"
title = "[SomaFM] SF 10-33: Ambient music mixed with the sounds of San Francisco public safety radio traffic."

[[track]]
path = "https://somafm.com/sonicuniverse.pls"
title = "[SomaFM] Sonic Universe: Transcending the world of jazz with eclectic, avant-garde takes on tradition."

[[track]]
path = "https://somafm.com/spacestation.pls"
title = "[SomaFM] Space Station Soma: Tune in, turn on, space out. Spaced-out ambient and mid-tempo electronica."

[[track]]
path = "https://somafm.com/specials.pls"
title = "[SomaFM] Specials: Now featuring Afternoon Jazz, Wavepool, DubX, The Surf Report & More!"

[[track]]
path = "https://somafm.com/synphaera.pls"
title = "[SomaFM] Synphaera Radio: Featuring the music from an independent record label focused on modern electronic ambient and space music."

[[track]]
path = "https://somafm.com/darkzone.pls"
title = "[SomaFM] The Dark Zone: The darker side of deep ambient. Music for staring into the Abyss."

[[track]]
path = "https://somafm.com/insound.pls"
title = "[SomaFM] The In-Sound: 60s/70s Hipster Euro Pop where psychedelic melodies meets groovy vibes."
