[[track]]
path = "/Users/tim/dev/dotfiles/cliamp/playlists/audio/spiral-ambient-cosmic-funk.mp3"
title = "Cosmic Funk Journey | Deep Groovy G-Funk, & Hypnotic space Mix"
artist = "Spiral Ambient"
duration_secs = 3892
bookmark = true
