[[track]]
path = "https://www.youtube.com/watch?v=7Cr5XtcviPo"
title = "ODYSSEY to Cosmic Funk  | Deep Grooves & Broken Beats Space Mix"
artist = "Spiral Ambient"
duration_secs = 4367

[[track]]
path = "https://www.youtube.com/watch?v=M653ML3FRNM"
title = "🎶 The Unreal Radio Stream⚡️WINAMP plays Unreal Tournament OST 🤘"
artist = "Nanotech Studios"

[[track]]
path = "https://www.youtube.com/watch?v=qRi1QsOGMUM"
title = "low cortisol jazz for overthinkers."
artist = "SILEO"
duration_secs = 7200

[[track]]
path = "https://www.youtube.com/watch?v=YwJ0N6TTfb8"
title = "jungle DnB galaxy 🚀🌌 a jungle drum and bass mix 👽"
artist = "Jellati"
duration_secs = 5111

[[track]]
path = "https://www.youtube.com/watch?v=f6k0FlHGrZE"
title = "Mark Farina - Mushroom Jazz 2"
artist = "erwinorb"
duration_secs = 4238

[[track]]
path = "https://www.youtube.com/watch?v=Y9jp7UrBtbM"
title = "Mark Farina - Mushroom Jazz 3 [Full Mixtape]"
artist = "Matt Katar"
duration_secs = 4334
